version: '3.1'
services:
  odoo-web:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}:${WEB_IMAGE_TAG}
    build: ./
    depends_on:
      - odoo-db
    ports:
      - "${WEB_PORT}:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-customize:/mnt/extra-addons-customize
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
    
  odoo-db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}:${DB_TAG}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  pgadmin-odoo:
    container_name: pgadmin-demo
    image: dpage/pgadmin4:5.4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:80
    links:
      - "odoo-db:pgsql-server"
    environment:
      PGADMIN_DEFAULT_EMAIL: shane@odootraining.ddns.net
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - odoo-db
    restart: always

  nginx-odoo:
    container_name: nginx-odoo
    build:
      context: ./dockerfilecarp
      dockerfile: nginx.Dockerfile
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    ports:
      - 80:80   #non secure
      - 443:443 #ssl
    depends_on:
      - odoo-web
    restart: always
volumes:
  odoo-db-data:
  odoo-web-data:
  pgadmin-data: